---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - hashivault_write:
        secret: 'services/carrier/pluto'
        data:
            pluto_auth_token: '{{ data[env].pluto_auth_token }}'


    # - name: lookup ssm parameter store in nominated aws profile
    #   debug: msg="{{ lookup('aws_ssm', 'dev/emailverification/briteverify' ) }}"

    # - name: Create or update key/value pair in aws parameter store
    #   aws_ssm_parameter_store:
    #     name: "Hello"
    #     description: "This is your first key"
    #     value: "World"

    # - name: lookup ssm parameter store in nominated aws profile
    #   debug: msg="{{ lookup('aws_ssm', 'Hello' ) }}"


# cat jwt_dev.key | ansible-vault encrypt_string --vault-id @prompt --stdin-name 'private_key'
# ansible-playbook vault-secrets.yml --vault-id @prompt --extra-vars "env=dev"